# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0002_newcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Newcar',
        ),
    ]
