# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0003_auto_20171123_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='paytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytype', models.CharField(max_length=50)),
            ],
        ),
    ]
