# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0004_paytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_date', models.DateField()),
                ('payee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simon.payee')),
            ],
        ),
    ]
