# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payee_id',
            new_name='payee',
        ),
    ]
