# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0006_auto_20171125_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
