# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simon', '0007_auto_20171125_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simon.paytype'),
        ),
    ]
